version: "3"

services:

  generate-delivery:
    tty: true
    stdin_open: true
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    image: ghcr.io/jinyoung/gpt-engineer:v5
    # command: ["-sh"]
    volumes:
      - ../delivery:/project