name: CI to Docker Hub
on:
  push:
    branches: [ main ]

jobs:

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1 
        with:
          # username: ${{ secrets.DOCKER_HUB_USERNAME }}
          # password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          username: apexacme
          password: sjdznf2127          

      - name: Build Maven Projects
        run: |
          mvn clean package  -f delivery/pom.xml -Dmaven.test.skip=true
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./delivery
          push: true
          tags: apexacme/ai-order:latest
