name: CI to Docker Hub
on:
  push:
    branches: [ main ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin' # AdoptOpenJDK의 후속 프로젝트

      - name: Log in to Docker Hub
        uses: docker/login-action@v1 
        with:
          # Always use secrets for usernames and passwords in GitHub Actions!
          username: apexacme
          password: sjdznf2127          

      - name: Build Maven Projects
        run: |
          mvn clean package -f delivery/pom.xml -Dmaven.test.skip=true
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./delivery
          push: true
          tags: apexacme/ai-order:latest
